# build stage
FROM node:16.13.2-slim as build-stage
# set working directory
RUN mkdir /app
WORKDIR /app
ADD ./src /app/src
ADD ./public /app/public
COPY package*.json ./
COPY *.html ./
COPY vite.config.js ./
RUN npm install
#COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
# Uncomment the line after to override default config
#COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]